---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: event_date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: sub_heading
  label: Sub Heading
  type: text
  hidden: false
  default: ''
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
pages:
- _careers/events-officer.md
- _careers/sponsorship-officer.md
- _events/investing-in-public-vs-private-firms.md
- _projects/mastercard.md
